### ISSUE TITLE
startMonitoringSignificantLocationChanges works?

### ISSUE THREAD

**Issue by basememara** [ethemozcan/QiblaDirection#1]
Assalaam Alaikum, Jazak'Allah Khair for providing this!

I am using iOS8 and I haven't had any luck getting `startMonitoringSignificantLocationChanges` to fire in my other apps, so I have resorted to `startUpdatingLocation` with a `distanceFilter` of 1000 meters.

Even while creating a demo app with QiblaDirection, `qiblaAngleDidChanged` doesn't fire unless I change your source code from `startMonitoringSignificantLocationChanges` to `startUpdatingLocation`. 

I believe the issue is that `startMonitoringSignificantLocationChanges` ONLY works in conjunction with 'locationManager.requestAlwaysAuthorization()' instead of with `locationManager.requestWhenInUseAuthorization()`. I have tested this and it does seem to be the case. Here is a StackOverflow on this: http://stackoverflow.com/questions/24529327/startmonitoringsignificantlocationchanges-not-working-with-swift-in-xcode-6-be

**Comment by ethemozcan** [comment]
Hello Basem,

Thank you for your contribution, I've merged your commits to my repo.

**Comment by basememara** [comment]
Awesome! Can you update the podspec and deploy to CocoaPods pls?
